theme: jekyll-theme-minimal
title: Dongyan Lin / 林冬妍
description: Hi, my name is Dongyan. I am a graduate student in computational neuroscience at McGill University.


# main text of home
name: Dongyan Lin / 林冬妍
bio: I really like star wars movies, but not including the sequels.

# twitter summary info
# description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
#external-image: false
#picture: assets/images/ant_square.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://drive.google.com/file/d/1lv-oIRGnEws2R8V36MnhAXDMtI3uvKfZ/view?usp=sharing
#resume-url: assets/CV_2019-06-06.pdf

#url: https://koppl.in/indigo
#your url: http://dongyanl1n.github.io

#permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
#disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: dongyanl1n
twitter: dongyanl1n
# google: mygoogle
instagram: dongyanl1n
# pinterest: mypinterest
linkedin: dongyanl1n
# youtube: myyoutube
# spotify: myspotify
github: dongyanl1n
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
email: dongyan.lin AT mail.mcgill.ca

authors:
    dongyanlin:
        name: Dongyan Lin
        bio: ???
#        external-image: false
#        picture: assets/images/ant_square.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
#width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
#blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
