theme: jekyll-theme-midnight
title: Dongyan Lin / 林冬妍
email: dongyan.lin@mail.mcgill.ca
description: Hi, my name is Dongyan. I am a graduate student in computational neuroscience at McGill University.
twitter_username: dongyanl1n
github_username: dongyanl1n
